SELECT *
  FROM (SELECT INOUTDATE,
			   WHCODE,
			   COUNT(*) AS CNT
		  FROM TB_StockMMrec
		 WHERE INOUTQTY > 1000
		   AND INOUTFLAG = 'I'
	  GROUP BY INOUTDATE, WHCODE) AA
 WHERE AA.CNT >= 2
 ORDER BY INOUTDATE ASC