

SELECT *
  FROM TB_User A JOIN(SELECT MAJORCODE
					  FROM TB_Standard
					 WHERE MAJORCODE = 'DEPTCODE')
					    ON 
 WHERE USERID LIKE '%%'
   AND USERNAME LIKE '%%'

 
SELECT USERID,
	   USERNAME,
	   PW,
	   T_COUNT AS PW_F_CNT,
	   DEPTCODE,
	   MAKEDATE,
	   MAKER,
	   EDITDATE,
	   EDITOR
  FROM TB_User 
 WHERE USERID LIKE '%%'
   AND USERNAME LIKE '%%'
   AND DEPTCODE = 'MM'